MEMORY_TYPE_DAILY_RAW = "daily_raw"
MEMORY_TYPE_DAILY_SUMMARY = "daily_summary"
MEMORY_TYPE_LEVEL_10 = "level_10"
MEMORY_TYPE_LEVEL_100 = "level_100"
MEMORY_TYPE_LEVEL_1000 = "level_1000"
MEMORY_TYPE_LEVEL_ARCHIVE = "level_archive"

MEMORY_HIERARCHY = {
    MEMORY_TYPE_DAILY_RAW: 0,
    MEMORY_TYPE_DAILY_SUMMARY: 1,
    MEMORY_TYPE_LEVEL_10: 2,
    MEMORY_TYPE_LEVEL_100: 3,
    MEMORY_TYPE_LEVEL_1000: 4,
    MEMORY_TYPE_LEVEL_ARCHIVE: 5
}

MEMORY_TYPE_DAYS = {
    MEMORY_TYPE_DAILY_RAW: 1,
    MEMORY_TYPE_DAILY_SUMMARY: 1,
    MEMORY_TYPE_LEVEL_10: 10,
    MEMORY_TYPE_LEVEL_100: 100,
    MEMORY_TYPE_LEVEL_1000: 1000,
    MEMORY_TYPE_LEVEL_ARCHIVE: float('inf')
}
